config {
    type: "table",
    description: "A table containing possible question response choices.",
    columns: {
      question_id: "The identifier for the question in a specific survey wave. Get this from the questions table.",
      src_coumn_name: "The name of the column containing the coded value of the response choice.",
      choice_value: "The coded value received in the data.",
      choice_text: "The text which was presented the user when making a selection.",
    },
    assertions : {
      uniqueKey: ["question_id", "src_column_name", "choice_value"],
    }
}

SELECT
  *
FROM
  UNNEST( ARRAY<STRUCT<question_id STRING, src_column_name STRING, choice_value STRING, choice_text STRING>>[
    -- bmg wave 13 questions
    -- ql5
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '1', 'Very satisfied'),
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '2', 'Fairly satisfied'),
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '3', 'Neither satisfied nor dissatisfied'),
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '4', 'Fairly dissatisfied'),
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '5', 'Very dissatisfied'),
    ('fdffbe47c37426d2450fa81e3438a971', 'ql5', '6', "Don't know"),
    -- ql7
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '1', 'Smartphone'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '2', 'Laptop'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '3', 'Desktop computer'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '4', 'Tablet'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '5', 'Smart device (e.g. smart speaker, smart TV, games console)'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '95', 'Other'),
    ('024e446e3c902d1476b7a28973a5ca7c', 'ql7', '97', "Don't know"),
    -- ql7a_1
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '1', 'Strongly agree'),
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '2', 'Agree'),
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '3', 'Neither agree nor disagree'),
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '4', 'Disagree'),
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '5', 'Strongly disagree'),
    ('47602fd5a2a938e128b72a2e197db94c', 'ql7a_1', '6', "Don't know"),
    -- ql7a_2
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '1', 'Strongly agree'),
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '2', 'Agree'),
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '3', 'Neither agree nor disagree'),
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '4', 'Disagree'),
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '5', 'Strongly disagree'),
    ('9ed80494f02187065fe551cfe5b41a2d', 'ql7a_2', '6', "Don't know"),
    -- ql7a_3
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '1', 'Strongly agree'),
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '2', 'Agree'),
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '3', 'Neither agree nor disagree'),
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '4', 'Disagree'),
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '5', 'Strongly disagree'),
    ('b24c36c47095712c1f366397592fa29a', 'ql7a_3', '6', "Don't know"),
    -- ql7a_4
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '1', 'Strongly agree'),
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '2', 'Agree'),
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '3', 'Neither agree nor disagree'),
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '4', 'Disagree'),
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '5', 'Strongly disagree'),
    ('2bedef3e3362c18bffd171e350acd01b', 'ql7a_4', '6', "Don't know"),
    -- ql7a_5
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '1', 'Strongly agree'),
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '2', 'Agree'),
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '3', 'Neither agree nor disagree'),
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '4', 'Disagree'),
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '5', 'Strongly disagree'),
    ('88f0343d942755da4e2749dd9435ae61', 'ql7a_5', '6', "Don't know"),
    -- ql7a_6
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '1', 'Strongly agree'),
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '2', 'Agree'),
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '3', 'Neither agree nor disagree'),
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '4', 'Disagree'),
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '5', 'Strongly disagree'),
    ('8db850ba874cd5ca17e673ef6bd60ded', 'ql7a_6', '6', "Don't know"),
    -- ql7a_7
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '1', 'Strongly agree'),
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '2', 'Agree'),
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '3', 'Neither agree nor disagree'),
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '4', 'Disagree'),
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '5', 'Strongly disagree'),
    ('0ef50d065f6b542ca49c551f2c907271', 'ql7a_7', '6', "Don't know"),
    -- ql7a_8
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '1', 'Strongly agree'),
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '2', 'Agree'),
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '3', 'Neither agree nor disagree'),
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '4', 'Disagree'),
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '5', 'Strongly disagree'),
    ('4c02e8419b4a8d5b63ac8109a0b4fa24', 'ql7a_8', '6', "Don't know"),
    -- ql1a
    ('be5476a11a964d710455b344e978595e', 'ql1a_3', '1', "Benefits - including eligibility, appeals, tax credits and Universal Credit"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_4', '1', "Births, deaths, marriages and care - including parenting, civil partnerships, divorce and Lasting Power of Attorney"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_5', '1', "Business and self-employed - including tools and guidance for businesses"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_6', '1', "Childcare and parenting - including giving birth, fostering, adopting, benefits for children and childcare"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_7', '1', "Citizenship and living in the UK - including Voting, community participation, life in the UK, international projects"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_8', '1', "Crime, justice and the law - including Legal processes, courts and the police"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_9', '1', "Disabled people and services - including carers, your rights, benefits and the Equality Act"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_10', '1', "Driving and transport - including vehicle tax, MOT and driving licences"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_11', '1', "Education and learning - including schools, colleges, student loans, university admissions and apprenticeships"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_12', '1', "Employing people - including pay, contracts and hiring"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_13', '1', "Environment and countryside - including flooding, recycling and wildlife"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_14', '1', "Housing and local services - including owning, renting and council services"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_15', '1', "Money and tax - including debt and Self Assessment"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_16', '1', "Passports, travel and living abroad - including renewing passports and travel advice by country"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_17', '1', "Visas and immigration - including applying to visit, work, study, settle or seek asylum in the UK"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_18', '1', "Working, jobs and pensions - including holiday entitlement and finding a job"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_19', '1', "Ukraine - impact on the UK, travel advice, sponsorship scheme"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_20', '1', "Cost of Living Support - This includes income and disability benefits, bills and allowances, childcare, housing and travel"),
    ('be5476a11a964d710455b344e978595e', 'ql1a_96', '1', "None of the above"),
    -- ql1c_3
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_1', '1', "Local council website"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_2', '1', "Government website (e.g. GOV.UK, GOV.WALES, GOV.SCOT, NIDIRECT)"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_3', '1', "NHS website"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_4', '1', "Social media (e.g. Facebook, Twitter, Instagram)"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_5', '1', "Search engines (e.g. Google)"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_6', '1', "Radio"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_7', '1', "TV"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_8', '1', "Newspaper"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_9', '1', "Magazine"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_10', '1', "Word of mouth"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_11', '1', "AI chatbot (e.g. ChatGPT, Copilot, Gemini)"),
    ('5621ec1c9d78dbf7e2998dcbcb157150', 'ql1c_3_95', '1', "Other")
    ] )