name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    name: 'Dependency Review scan'
    uses: alphagov/govuk-infrastructure/.github/workflows/dependency-review.yml@main
